//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CollectionTypeAdapterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CollectionTypeAdapterFactory")
#ifdef RESTRICT_CollectionTypeAdapterFactory
#define INCLUDE_ALL_CollectionTypeAdapterFactory 0
#else
#define INCLUDE_ALL_CollectionTypeAdapterFactory 1
#endif
#undef RESTRICT_CollectionTypeAdapterFactory

#if !defined (GsonCollectionTypeAdapterFactory_) && (INCLUDE_ALL_CollectionTypeAdapterFactory || defined(INCLUDE_GsonCollectionTypeAdapterFactory))
#define GsonCollectionTypeAdapterFactory_

#define RESTRICT_TypeAdapterFactory 1
#define INCLUDE_GsonTypeAdapterFactory 1
#include "TypeAdapterFactory.h"

@class GsonConstructorConstructor;
@class GsonGson;
@class GsonTypeAdapter;
@class GsonTypeToken;

@interface GsonCollectionTypeAdapterFactory : NSObject < GsonTypeAdapterFactory >

#pragma mark Public

- (instancetype)initWithGsonConstructorConstructor:(GsonConstructorConstructor *)constructorConstructor;

- (GsonTypeAdapter *)createWithGsonGson:(GsonGson *)gson
                      withGsonTypeToken:(GsonTypeToken *)typeToken;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonCollectionTypeAdapterFactory)

FOUNDATION_EXPORT void GsonCollectionTypeAdapterFactory_initWithGsonConstructorConstructor_(GsonCollectionTypeAdapterFactory *self, GsonConstructorConstructor *constructorConstructor);

FOUNDATION_EXPORT GsonCollectionTypeAdapterFactory *new_GsonCollectionTypeAdapterFactory_initWithGsonConstructorConstructor_(GsonConstructorConstructor *constructorConstructor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonCollectionTypeAdapterFactory *create_GsonCollectionTypeAdapterFactory_initWithGsonConstructorConstructor_(GsonConstructorConstructor *constructorConstructor);

J2OBJC_TYPE_LITERAL_HEADER(GsonCollectionTypeAdapterFactory)

@compatibility_alias ComGoogleGsonInternalBindCollectionTypeAdapterFactory GsonCollectionTypeAdapterFactory;

#endif

#pragma pop_macro("INCLUDE_ALL_CollectionTypeAdapterFactory")
