//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ConstructorConstructor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ConstructorConstructor")
#ifdef RESTRICT_ConstructorConstructor
#define INCLUDE_ALL_ConstructorConstructor 0
#else
#define INCLUDE_ALL_ConstructorConstructor 1
#endif
#undef RESTRICT_ConstructorConstructor

#if !defined (GsonConstructorConstructor_) && (INCLUDE_ALL_ConstructorConstructor || defined(INCLUDE_GsonConstructorConstructor))
#define GsonConstructorConstructor_

@class GsonTypeToken;
@protocol GsonObjectConstructor;
@protocol JavaUtilMap;

@interface GsonConstructorConstructor : NSObject

#pragma mark Public

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)instanceCreators;

- (id<GsonObjectConstructor>)getWithGsonTypeToken:(GsonTypeToken *)typeToken;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonConstructorConstructor)

FOUNDATION_EXPORT void GsonConstructorConstructor_initWithJavaUtilMap_(GsonConstructorConstructor *self, id<JavaUtilMap> instanceCreators);

FOUNDATION_EXPORT GsonConstructorConstructor *new_GsonConstructorConstructor_initWithJavaUtilMap_(id<JavaUtilMap> instanceCreators) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonConstructorConstructor *create_GsonConstructorConstructor_initWithJavaUtilMap_(id<JavaUtilMap> instanceCreators);

J2OBJC_TYPE_LITERAL_HEADER(GsonConstructorConstructor)

@compatibility_alias ComGoogleGsonInternalConstructorConstructor GsonConstructorConstructor;

#endif

#pragma pop_macro("INCLUDE_ALL_ConstructorConstructor")
