//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonSerializationContext.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonSerializationContext")
#ifdef RESTRICT_JsonSerializationContext
#define INCLUDE_ALL_JsonSerializationContext 0
#else
#define INCLUDE_ALL_JsonSerializationContext 1
#endif
#undef RESTRICT_JsonSerializationContext

#if !defined (GsonJsonSerializationContext_) && (INCLUDE_ALL_JsonSerializationContext || defined(INCLUDE_GsonJsonSerializationContext))
#define GsonJsonSerializationContext_

@class GsonJsonElement;
@protocol JavaLangReflectType;

@protocol GsonJsonSerializationContext < JavaObject >

- (GsonJsonElement *)serializeWithId:(id)src;

- (GsonJsonElement *)serializeWithId:(id)src
             withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonJsonSerializationContext)

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonSerializationContext)

#define ComGoogleGsonJsonSerializationContext GsonJsonSerializationContext

#endif

#pragma pop_macro("INCLUDE_ALL_JsonSerializationContext")
