//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonStreamParser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonStreamParser")
#ifdef RESTRICT_JsonStreamParser
#define INCLUDE_ALL_JsonStreamParser 0
#else
#define INCLUDE_ALL_JsonStreamParser 1
#endif
#undef RESTRICT_JsonStreamParser

#if !defined (GsonJsonStreamParser_) && (INCLUDE_ALL_JsonStreamParser || defined(INCLUDE_GsonJsonStreamParser))
#define GsonJsonStreamParser_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class GsonJsonElement;
@class JavaIoReader;
@protocol JavaUtilFunctionConsumer;

@interface GsonJsonStreamParser : NSObject < JavaUtilIterator >

#pragma mark Public

- (instancetype)initWithJavaIoReader:(JavaIoReader *)reader;

- (instancetype)initWithNSString:(NSString *)json;

- (jboolean)hasNext;

- (GsonJsonElement *)next;

- (void)remove;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonJsonStreamParser)

FOUNDATION_EXPORT void GsonJsonStreamParser_initWithNSString_(GsonJsonStreamParser *self, NSString *json);

FOUNDATION_EXPORT GsonJsonStreamParser *new_GsonJsonStreamParser_initWithNSString_(NSString *json) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonStreamParser *create_GsonJsonStreamParser_initWithNSString_(NSString *json);

FOUNDATION_EXPORT void GsonJsonStreamParser_initWithJavaIoReader_(GsonJsonStreamParser *self, JavaIoReader *reader);

FOUNDATION_EXPORT GsonJsonStreamParser *new_GsonJsonStreamParser_initWithJavaIoReader_(JavaIoReader *reader) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonStreamParser *create_GsonJsonStreamParser_initWithJavaIoReader_(JavaIoReader *reader);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonStreamParser)

@compatibility_alias ComGoogleGsonJsonStreamParser GsonJsonStreamParser;

#endif

#pragma pop_macro("INCLUDE_ALL_JsonStreamParser")
