//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ObjectConstructor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObjectConstructor")
#ifdef RESTRICT_ObjectConstructor
#define INCLUDE_ALL_ObjectConstructor 0
#else
#define INCLUDE_ALL_ObjectConstructor 1
#endif
#undef RESTRICT_ObjectConstructor

#if !defined (GsonObjectConstructor_) && (INCLUDE_ALL_ObjectConstructor || defined(INCLUDE_GsonObjectConstructor))
#define GsonObjectConstructor_

@protocol GsonObjectConstructor < JavaObject >

- (id)construct;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonObjectConstructor)

J2OBJC_TYPE_LITERAL_HEADER(GsonObjectConstructor)

#define ComGoogleGsonInternalObjectConstructor GsonObjectConstructor

#endif

#pragma pop_macro("INCLUDE_ALL_ObjectConstructor")
