//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Primitives.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Primitives")
#ifdef RESTRICT_Primitives
#define INCLUDE_ALL_Primitives 0
#else
#define INCLUDE_ALL_Primitives 1
#endif
#undef RESTRICT_Primitives

#if !defined (GsonPrimitives_) && (INCLUDE_ALL_Primitives || defined(INCLUDE_GsonPrimitives))
#define GsonPrimitives_

@class IOSClass;
@protocol JavaLangReflectType;

@interface GsonPrimitives : NSObject

#pragma mark Public

+ (jboolean)isPrimitiveWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (jboolean)isWrapperTypeWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (IOSClass *)unwrapWithIOSClass:(IOSClass *)type;

+ (IOSClass *)wrapWithIOSClass:(IOSClass *)type;

@end

J2OBJC_STATIC_INIT(GsonPrimitives)

FOUNDATION_EXPORT jboolean GsonPrimitives_isPrimitiveWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT jboolean GsonPrimitives_isWrapperTypeWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT IOSClass *GsonPrimitives_wrapWithIOSClass_(IOSClass *type);

FOUNDATION_EXPORT IOSClass *GsonPrimitives_unwrapWithIOSClass_(IOSClass *type);

J2OBJC_TYPE_LITERAL_HEADER(GsonPrimitives)

@compatibility_alias ComGoogleGsonInternalPrimitives GsonPrimitives;

#endif

#pragma pop_macro("INCLUDE_ALL_Primitives")
