//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ReflectiveTypeAdapterFactory.java
//

#include "$Gson$Types.h"
#include "ConstructorConstructor.h"
#include "Excluder.h"
#include "FieldNamingStrategy.h"
#include "Gson.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "JsonAdapter.h"
#include "JsonAdapterAnnotationTypeAdapterFactory.h"
#include "JsonReader.h"
#include "JsonSyntaxException.h"
#include "JsonToken.h"
#include "JsonWriter.h"
#include "ObjectConstructor.h"
#include "Primitives.h"
#include "ReflectiveTypeAdapterFactory.h"
#include "SerializedName.h"
#include "TypeAdapter.h"
#include "TypeAdapterRuntimeTypeWrapper.h"
#include "TypeToken.h"
#include "java/lang/AssertionError.h"
#include "java/lang/IllegalAccessException.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/reflect/Field.h"
#include "java/lang/reflect/Type.h"
#include "java/util/Collection.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/Map.h"

@interface GsonReflectiveTypeAdapterFactory () {
 @public
  GsonConstructorConstructor *constructorConstructor_;
  id<GsonFieldNamingStrategy> fieldNamingPolicy_;
  GsonExcluder *excluder_;
}

- (NSString *)getFieldNameWithJavaLangReflectField:(JavaLangReflectField *)f;

- (GsonReflectiveTypeAdapterFactory_BoundField *)createBoundFieldWithGsonGson:(GsonGson *)context
                                                     withJavaLangReflectField:(JavaLangReflectField *)field
                                                                 withNSString:(NSString *)name
                                                            withGsonTypeToken:(GsonTypeToken *)fieldType
                                                                  withBoolean:(jboolean)serialize
                                                                  withBoolean:(jboolean)deserialize;

- (GsonTypeAdapter *)getFieldAdapterWithGsonGson:(GsonGson *)gson
                        withJavaLangReflectField:(JavaLangReflectField *)field
                               withGsonTypeToken:(GsonTypeToken *)fieldType;

- (id<JavaUtilMap>)getBoundFieldsWithGsonGson:(GsonGson *)context
                            withGsonTypeToken:(GsonTypeToken *)type
                                 withIOSClass:(IOSClass *)raw;

@end

J2OBJC_FIELD_SETTER(GsonReflectiveTypeAdapterFactory, constructorConstructor_, GsonConstructorConstructor *)
J2OBJC_FIELD_SETTER(GsonReflectiveTypeAdapterFactory, fieldNamingPolicy_, id<GsonFieldNamingStrategy>)
J2OBJC_FIELD_SETTER(GsonReflectiveTypeAdapterFactory, excluder_, GsonExcluder *)

__attribute__((unused)) static NSString *GsonReflectiveTypeAdapterFactory_getFieldNameWithJavaLangReflectField_(GsonReflectiveTypeAdapterFactory *self, JavaLangReflectField *f);

__attribute__((unused)) static GsonReflectiveTypeAdapterFactory_BoundField *GsonReflectiveTypeAdapterFactory_createBoundFieldWithGsonGson_withJavaLangReflectField_withNSString_withGsonTypeToken_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory *self, GsonGson *context, JavaLangReflectField *field, NSString *name, GsonTypeToken *fieldType, jboolean serialize, jboolean deserialize);

__attribute__((unused)) static GsonTypeAdapter *GsonReflectiveTypeAdapterFactory_getFieldAdapterWithGsonGson_withJavaLangReflectField_withGsonTypeToken_(GsonReflectiveTypeAdapterFactory *self, GsonGson *gson, JavaLangReflectField *field, GsonTypeToken *fieldType);

__attribute__((unused)) static id<JavaUtilMap> GsonReflectiveTypeAdapterFactory_getBoundFieldsWithGsonGson_withGsonTypeToken_withIOSClass_(GsonReflectiveTypeAdapterFactory *self, GsonGson *context, GsonTypeToken *type, IOSClass *raw);

@interface GsonReflectiveTypeAdapterFactory_1 : GsonReflectiveTypeAdapterFactory_BoundField {
 @public
  GsonGson *val$context_;
  JavaLangReflectField *val$field_;
  GsonTypeToken *val$fieldType_;
  jboolean val$isPrimitive_;
  GsonTypeAdapter *typeAdapter_;
}

- (instancetype)initWithGsonReflectiveTypeAdapterFactory:(GsonReflectiveTypeAdapterFactory *)outer$
                                            withGsonGson:(GsonGson *)capture$0
                                withJavaLangReflectField:(JavaLangReflectField *)capture$1
                                       withGsonTypeToken:(GsonTypeToken *)capture$2
                                             withBoolean:(jboolean)capture$3
                                            withNSString:(NSString *)name
                                             withBoolean:(jboolean)serialized
                                             withBoolean:(jboolean)deserialized;

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)writer
                         withId:(id)value;

- (void)readWithGsonJsonReader:(GsonJsonReader *)reader
                        withId:(id)value;

- (jboolean)writeFieldWithId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonReflectiveTypeAdapterFactory_1)

J2OBJC_FIELD_SETTER(GsonReflectiveTypeAdapterFactory_1, typeAdapter_, GsonTypeAdapter *)

__attribute__((unused)) static void GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory_1 *self, GsonReflectiveTypeAdapterFactory *outer$, GsonGson *capture$0, JavaLangReflectField *capture$1, GsonTypeToken *capture$2, jboolean capture$3, NSString *name, jboolean serialized, jboolean deserialized);

__attribute__((unused)) static GsonReflectiveTypeAdapterFactory_1 *new_GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory *outer$, GsonGson *capture$0, JavaLangReflectField *capture$1, GsonTypeToken *capture$2, jboolean capture$3, NSString *name, jboolean serialized, jboolean deserialized) NS_RETURNS_RETAINED;

__attribute__((unused)) static GsonReflectiveTypeAdapterFactory_1 *create_GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory *outer$, GsonGson *capture$0, JavaLangReflectField *capture$1, GsonTypeToken *capture$2, jboolean capture$3, NSString *name, jboolean serialized, jboolean deserialized);

@interface GsonReflectiveTypeAdapterFactory_Adapter () {
 @public
  id<GsonObjectConstructor> constructor_;
  id<JavaUtilMap> boundFields_;
}

- (instancetype)initWithGsonObjectConstructor:(id<GsonObjectConstructor>)constructor
                              withJavaUtilMap:(id<JavaUtilMap>)boundFields;

@end

J2OBJC_FIELD_SETTER(GsonReflectiveTypeAdapterFactory_Adapter, constructor_, id<GsonObjectConstructor>)
J2OBJC_FIELD_SETTER(GsonReflectiveTypeAdapterFactory_Adapter, boundFields_, id<JavaUtilMap>)

__attribute__((unused)) static void GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(GsonReflectiveTypeAdapterFactory_Adapter *self, id<GsonObjectConstructor> constructor, id<JavaUtilMap> boundFields);

__attribute__((unused)) static GsonReflectiveTypeAdapterFactory_Adapter *new_GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(id<GsonObjectConstructor> constructor, id<JavaUtilMap> boundFields) NS_RETURNS_RETAINED;

__attribute__((unused)) static GsonReflectiveTypeAdapterFactory_Adapter *create_GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(id<GsonObjectConstructor> constructor, id<JavaUtilMap> boundFields);

@implementation GsonReflectiveTypeAdapterFactory

- (instancetype)initWithGsonConstructorConstructor:(GsonConstructorConstructor *)constructorConstructor
                       withGsonFieldNamingStrategy:(id<GsonFieldNamingStrategy>)fieldNamingPolicy
                                  withGsonExcluder:(GsonExcluder *)excluder {
  GsonReflectiveTypeAdapterFactory_initWithGsonConstructorConstructor_withGsonFieldNamingStrategy_withGsonExcluder_(self, constructorConstructor, fieldNamingPolicy, excluder);
  return self;
}

- (jboolean)excludeFieldWithJavaLangReflectField:(JavaLangReflectField *)f
                                     withBoolean:(jboolean)serialize {
  return GsonReflectiveTypeAdapterFactory_excludeFieldWithJavaLangReflectField_withBoolean_withGsonExcluder_(f, serialize, excluder_);
}

+ (jboolean)excludeFieldWithJavaLangReflectField:(JavaLangReflectField *)f
                                     withBoolean:(jboolean)serialize
                                withGsonExcluder:(GsonExcluder *)excluder {
  return GsonReflectiveTypeAdapterFactory_excludeFieldWithJavaLangReflectField_withBoolean_withGsonExcluder_(f, serialize, excluder);
}

- (NSString *)getFieldNameWithJavaLangReflectField:(JavaLangReflectField *)f {
  return GsonReflectiveTypeAdapterFactory_getFieldNameWithJavaLangReflectField_(self, f);
}

+ (NSString *)getFieldNameWithGsonFieldNamingStrategy:(id<GsonFieldNamingStrategy>)fieldNamingPolicy
                             withJavaLangReflectField:(JavaLangReflectField *)f {
  return GsonReflectiveTypeAdapterFactory_getFieldNameWithGsonFieldNamingStrategy_withJavaLangReflectField_(fieldNamingPolicy, f);
}

- (GsonTypeAdapter *)createWithGsonGson:(GsonGson *)gson
                      withGsonTypeToken:(GsonTypeToken *)type {
  IOSClass *raw = [((GsonTypeToken *) nil_chk(type)) getRawType];
  if (![NSObject_class_() isAssignableFrom:raw]) {
    return nil;
  }
  id<GsonObjectConstructor> constructor = [((GsonConstructorConstructor *) nil_chk(constructorConstructor_)) getWithGsonTypeToken:type];
  return new_GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(constructor, GsonReflectiveTypeAdapterFactory_getBoundFieldsWithGsonGson_withGsonTypeToken_withIOSClass_(self, gson, type, raw));
}

- (GsonReflectiveTypeAdapterFactory_BoundField *)createBoundFieldWithGsonGson:(GsonGson *)context
                                                     withJavaLangReflectField:(JavaLangReflectField *)field
                                                                 withNSString:(NSString *)name
                                                            withGsonTypeToken:(GsonTypeToken *)fieldType
                                                                  withBoolean:(jboolean)serialize
                                                                  withBoolean:(jboolean)deserialize {
  return GsonReflectiveTypeAdapterFactory_createBoundFieldWithGsonGson_withJavaLangReflectField_withNSString_withGsonTypeToken_withBoolean_withBoolean_(self, context, field, name, fieldType, serialize, deserialize);
}

- (GsonTypeAdapter *)getFieldAdapterWithGsonGson:(GsonGson *)gson
                        withJavaLangReflectField:(JavaLangReflectField *)field
                               withGsonTypeToken:(GsonTypeToken *)fieldType {
  return GsonReflectiveTypeAdapterFactory_getFieldAdapterWithGsonGson_withJavaLangReflectField_withGsonTypeToken_(self, gson, field, fieldType);
}

- (id<JavaUtilMap>)getBoundFieldsWithGsonGson:(GsonGson *)context
                            withGsonTypeToken:(GsonTypeToken *)type
                                 withIOSClass:(IOSClass *)raw {
  return GsonReflectiveTypeAdapterFactory_getBoundFieldsWithGsonGson_withGsonTypeToken_withIOSClass_(self, context, type, raw);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "Z", 0x8, 1, 3, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x2, 4, 5, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x8, 4, 6, -1, -1, -1, -1 },
    { NULL, "LGsonTypeAdapter;", 0x1, 7, 8, -1, 9, -1, -1 },
    { NULL, "LGsonReflectiveTypeAdapterFactory_BoundField;", 0x2, 10, 11, -1, 12, -1, -1 },
    { NULL, "LGsonTypeAdapter;", 0x2, 13, 14, -1, 15, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x2, 16, 17, -1, 18, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithGsonConstructorConstructor:withGsonFieldNamingStrategy:withGsonExcluder:);
  methods[1].selector = @selector(excludeFieldWithJavaLangReflectField:withBoolean:);
  methods[2].selector = @selector(excludeFieldWithJavaLangReflectField:withBoolean:withGsonExcluder:);
  methods[3].selector = @selector(getFieldNameWithJavaLangReflectField:);
  methods[4].selector = @selector(getFieldNameWithGsonFieldNamingStrategy:withJavaLangReflectField:);
  methods[5].selector = @selector(createWithGsonGson:withGsonTypeToken:);
  methods[6].selector = @selector(createBoundFieldWithGsonGson:withJavaLangReflectField:withNSString:withGsonTypeToken:withBoolean:withBoolean:);
  methods[7].selector = @selector(getFieldAdapterWithGsonGson:withJavaLangReflectField:withGsonTypeToken:);
  methods[8].selector = @selector(getBoundFieldsWithGsonGson:withGsonTypeToken:withIOSClass:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "constructorConstructor_", "LGsonConstructorConstructor;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "fieldNamingPolicy_", "LGsonFieldNamingStrategy;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "excluder_", "LGsonExcluder;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LGsonConstructorConstructor;LGsonFieldNamingStrategy;LGsonExcluder;", "excludeField", "LJavaLangReflectField;Z", "LJavaLangReflectField;ZLGsonExcluder;", "getFieldName", "LJavaLangReflectField;", "LGsonFieldNamingStrategy;LJavaLangReflectField;", "create", "LGsonGson;LGsonTypeToken;", "<T:Ljava/lang/Object;>(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;", "createBoundField", "LGsonGson;LJavaLangReflectField;LNSString;LGsonTypeToken;ZZ", "(Lcom/google/gson/Gson;Ljava/lang/reflect/Field;Ljava/lang/String;Lcom/google/gson/reflect/TypeToken<*>;ZZ)Lcom/google/gson/internal/bind/ReflectiveTypeAdapterFactory$BoundField;", "getFieldAdapter", "LGsonGson;LJavaLangReflectField;LGsonTypeToken;", "(Lcom/google/gson/Gson;Ljava/lang/reflect/Field;Lcom/google/gson/reflect/TypeToken<*>;)Lcom/google/gson/TypeAdapter<*>;", "getBoundFields", "LGsonGson;LGsonTypeToken;LIOSClass;", "(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<*>;Ljava/lang/Class<*>;)Ljava/util/Map<Ljava/lang/String;Lcom/google/gson/internal/bind/ReflectiveTypeAdapterFactory$BoundField;>;", "LGsonReflectiveTypeAdapterFactory_BoundField;LGsonReflectiveTypeAdapterFactory_Adapter;" };
  static const J2ObjcClassInfo _GsonReflectiveTypeAdapterFactory = { "ReflectiveTypeAdapterFactory", "com.google.gson.internal.bind", ptrTable, methods, fields, 7, 0x11, 9, 3, -1, 19, -1, -1, -1 };
  return &_GsonReflectiveTypeAdapterFactory;
}

@end

void GsonReflectiveTypeAdapterFactory_initWithGsonConstructorConstructor_withGsonFieldNamingStrategy_withGsonExcluder_(GsonReflectiveTypeAdapterFactory *self, GsonConstructorConstructor *constructorConstructor, id<GsonFieldNamingStrategy> fieldNamingPolicy, GsonExcluder *excluder) {
  NSObject_init(self);
  self->constructorConstructor_ = constructorConstructor;
  self->fieldNamingPolicy_ = fieldNamingPolicy;
  self->excluder_ = excluder;
}

GsonReflectiveTypeAdapterFactory *new_GsonReflectiveTypeAdapterFactory_initWithGsonConstructorConstructor_withGsonFieldNamingStrategy_withGsonExcluder_(GsonConstructorConstructor *constructorConstructor, id<GsonFieldNamingStrategy> fieldNamingPolicy, GsonExcluder *excluder) {
  J2OBJC_NEW_IMPL(GsonReflectiveTypeAdapterFactory, initWithGsonConstructorConstructor_withGsonFieldNamingStrategy_withGsonExcluder_, constructorConstructor, fieldNamingPolicy, excluder)
}

GsonReflectiveTypeAdapterFactory *create_GsonReflectiveTypeAdapterFactory_initWithGsonConstructorConstructor_withGsonFieldNamingStrategy_withGsonExcluder_(GsonConstructorConstructor *constructorConstructor, id<GsonFieldNamingStrategy> fieldNamingPolicy, GsonExcluder *excluder) {
  J2OBJC_CREATE_IMPL(GsonReflectiveTypeAdapterFactory, initWithGsonConstructorConstructor_withGsonFieldNamingStrategy_withGsonExcluder_, constructorConstructor, fieldNamingPolicy, excluder)
}

jboolean GsonReflectiveTypeAdapterFactory_excludeFieldWithJavaLangReflectField_withBoolean_withGsonExcluder_(JavaLangReflectField *f, jboolean serialize, GsonExcluder *excluder) {
  GsonReflectiveTypeAdapterFactory_initialize();
  return ![((GsonExcluder *) nil_chk(excluder)) excludeClassWithIOSClass:[((JavaLangReflectField *) nil_chk(f)) getType] withBoolean:serialize] && ![excluder excludeFieldWithJavaLangReflectField:f withBoolean:serialize];
}

NSString *GsonReflectiveTypeAdapterFactory_getFieldNameWithJavaLangReflectField_(GsonReflectiveTypeAdapterFactory *self, JavaLangReflectField *f) {
  return GsonReflectiveTypeAdapterFactory_getFieldNameWithGsonFieldNamingStrategy_withJavaLangReflectField_(self->fieldNamingPolicy_, f);
}

NSString *GsonReflectiveTypeAdapterFactory_getFieldNameWithGsonFieldNamingStrategy_withJavaLangReflectField_(id<GsonFieldNamingStrategy> fieldNamingPolicy, JavaLangReflectField *f) {
  GsonReflectiveTypeAdapterFactory_initialize();
  id<GsonSerializedName> serializedName = ((id<GsonSerializedName>) [((JavaLangReflectField *) nil_chk(f)) getAnnotationWithIOSClass:GsonSerializedName_class_()]);
  return serializedName == nil ? [((id<GsonFieldNamingStrategy>) nil_chk(fieldNamingPolicy)) translateNameWithJavaLangReflectField:f] : [serializedName value];
}

GsonReflectiveTypeAdapterFactory_BoundField *GsonReflectiveTypeAdapterFactory_createBoundFieldWithGsonGson_withJavaLangReflectField_withNSString_withGsonTypeToken_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory *self, GsonGson *context, JavaLangReflectField *field, NSString *name, GsonTypeToken *fieldType, jboolean serialize, jboolean deserialize) {
  jboolean isPrimitive = GsonPrimitives_isPrimitiveWithJavaLangReflectType_([((GsonTypeToken *) nil_chk(fieldType)) getRawType]);
  return new_GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(self, context, field, fieldType, isPrimitive, name, serialize, deserialize);
}

GsonTypeAdapter *GsonReflectiveTypeAdapterFactory_getFieldAdapterWithGsonGson_withJavaLangReflectField_withGsonTypeToken_(GsonReflectiveTypeAdapterFactory *self, GsonGson *gson, JavaLangReflectField *field, GsonTypeToken *fieldType) {
  id<GsonJsonAdapter> annotation = ((id<GsonJsonAdapter>) [((JavaLangReflectField *) nil_chk(field)) getAnnotationWithIOSClass:GsonJsonAdapter_class_()]);
  if (annotation != nil) {
    GsonTypeAdapter *adapter = GsonJsonAdapterAnnotationTypeAdapterFactory_getTypeAdapterWithGsonConstructorConstructor_withGsonGson_withGsonTypeToken_withGsonJsonAdapter_(self->constructorConstructor_, gson, fieldType, annotation);
    if (adapter != nil) return adapter;
  }
  return [((GsonGson *) nil_chk(gson)) getAdapterWithGsonTypeToken:fieldType];
}

id<JavaUtilMap> GsonReflectiveTypeAdapterFactory_getBoundFieldsWithGsonGson_withGsonTypeToken_withIOSClass_(GsonReflectiveTypeAdapterFactory *self, GsonGson *context, GsonTypeToken *type, IOSClass *raw) {
  id<JavaUtilMap> result = new_JavaUtilLinkedHashMap_init();
  if ([((IOSClass *) nil_chk(raw)) isInterface]) {
    return result;
  }
  id<JavaLangReflectType> declaredType = [((GsonTypeToken *) nil_chk(type)) getType];
  while (raw != NSObject_class_()) {
    IOSObjectArray *fields = [((IOSClass *) nil_chk(raw)) getDeclaredFields];
    {
      IOSObjectArray *a__ = fields;
      JavaLangReflectField * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
      JavaLangReflectField * const *e__ = b__ + a__->size_;
      while (b__ < e__) {
        JavaLangReflectField *field = *b__++;
        jboolean serialize = [self excludeFieldWithJavaLangReflectField:field withBoolean:true];
        jboolean deserialize = [self excludeFieldWithJavaLangReflectField:field withBoolean:false];
        if (!serialize && !deserialize) {
          continue;
        }
        [((JavaLangReflectField *) nil_chk(field)) setAccessibleWithBoolean:true];
        id<JavaLangReflectType> fieldType = Gson_Gson_Types_resolveWithJavaLangReflectType_withIOSClass_withJavaLangReflectType_([type getType], raw, [field getGenericType]);
        GsonReflectiveTypeAdapterFactory_BoundField *boundField = GsonReflectiveTypeAdapterFactory_createBoundFieldWithGsonGson_withJavaLangReflectField_withNSString_withGsonTypeToken_withBoolean_withBoolean_(self, context, field, GsonReflectiveTypeAdapterFactory_getFieldNameWithJavaLangReflectField_(self, field), GsonTypeToken_getWithJavaLangReflectType_(fieldType), serialize, deserialize);
        GsonReflectiveTypeAdapterFactory_BoundField *previous = [result putWithId:((GsonReflectiveTypeAdapterFactory_BoundField *) nil_chk(boundField))->name_ withId:boundField];
        if (previous != nil) {
          @throw new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("@$$", declaredType, @" declares multiple JSON fields named ", previous->name_));
        }
      }
    }
    type = GsonTypeToken_getWithJavaLangReflectType_(Gson_Gson_Types_resolveWithJavaLangReflectType_withIOSClass_withJavaLangReflectType_([type getType], raw, [raw getGenericSuperclass]));
    raw = [((GsonTypeToken *) nil_chk(type)) getRawType];
  }
  return result;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GsonReflectiveTypeAdapterFactory)

@implementation GsonReflectiveTypeAdapterFactory_BoundField

- (instancetype)initWithNSString:(NSString *)name
                     withBoolean:(jboolean)serialized
                     withBoolean:(jboolean)deserialized {
  GsonReflectiveTypeAdapterFactory_BoundField_initWithNSString_withBoolean_withBoolean_(self, name, serialized, deserialized);
  return self;
}

- (jboolean)writeFieldWithId:(id)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)writer
                         withId:(id)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)readWithGsonJsonReader:(GsonJsonReader *)reader
                        withId:(id)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, 0, -1, -1, -1, -1 },
    { NULL, "Z", 0x400, 1, 2, 3, -1, -1, -1 },
    { NULL, "V", 0x400, 4, 5, 3, -1, -1, -1 },
    { NULL, "V", 0x400, 6, 7, 3, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:withBoolean:withBoolean:);
  methods[1].selector = @selector(writeFieldWithId:);
  methods[2].selector = @selector(writeWithGsonJsonWriter:withId:);
  methods[3].selector = @selector(readWithGsonJsonReader:withId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "name_", "LNSString;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "serialized_", "Z", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "deserialized_", "Z", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;ZZ", "writeField", "LNSObject;", "LJavaIoIOException;LJavaLangIllegalAccessException;", "write", "LGsonJsonWriter;LNSObject;", "read", "LGsonJsonReader;LNSObject;", "LGsonReflectiveTypeAdapterFactory;" };
  static const J2ObjcClassInfo _GsonReflectiveTypeAdapterFactory_BoundField = { "BoundField", "com.google.gson.internal.bind", ptrTable, methods, fields, 7, 0x408, 4, 3, 8, -1, -1, -1, -1 };
  return &_GsonReflectiveTypeAdapterFactory_BoundField;
}

@end

void GsonReflectiveTypeAdapterFactory_BoundField_initWithNSString_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory_BoundField *self, NSString *name, jboolean serialized, jboolean deserialized) {
  NSObject_init(self);
  self->name_ = name;
  self->serialized_ = serialized;
  self->deserialized_ = deserialized;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GsonReflectiveTypeAdapterFactory_BoundField)

@implementation GsonReflectiveTypeAdapterFactory_1

- (instancetype)initWithGsonReflectiveTypeAdapterFactory:(GsonReflectiveTypeAdapterFactory *)outer$
                                            withGsonGson:(GsonGson *)capture$0
                                withJavaLangReflectField:(JavaLangReflectField *)capture$1
                                       withGsonTypeToken:(GsonTypeToken *)capture$2
                                             withBoolean:(jboolean)capture$3
                                            withNSString:(NSString *)name
                                             withBoolean:(jboolean)serialized
                                             withBoolean:(jboolean)deserialized {
  GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(self, outer$, capture$0, capture$1, capture$2, capture$3, name, serialized, deserialized);
  return self;
}

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)writer
                         withId:(id)value {
  id fieldValue = [((JavaLangReflectField *) nil_chk(val$field_)) getWithId:value];
  GsonTypeAdapter *t = new_GsonTypeAdapterRuntimeTypeWrapper_initWithGsonGson_withGsonTypeAdapter_withJavaLangReflectType_(val$context_, self->typeAdapter_, [((GsonTypeToken *) nil_chk(val$fieldType_)) getType]);
  [t writeWithGsonJsonWriter:writer withId:fieldValue];
}

- (void)readWithGsonJsonReader:(GsonJsonReader *)reader
                        withId:(id)value {
  id fieldValue = [((GsonTypeAdapter *) nil_chk(typeAdapter_)) readWithGsonJsonReader:reader];
  if (fieldValue != nil || !val$isPrimitive_) {
    [((JavaLangReflectField *) nil_chk(val$field_)) setWithId:value withId:fieldValue];
  }
}

- (jboolean)writeFieldWithId:(id)value {
  if (!serialized_) return false;
  id fieldValue = [((JavaLangReflectField *) nil_chk(val$field_)) getWithId:value];
  return fieldValue != value;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 1, 2, 3, -1, -1, -1 },
    { NULL, "V", 0x0, 4, 5, 3, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, 3, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithGsonReflectiveTypeAdapterFactory:withGsonGson:withJavaLangReflectField:withGsonTypeToken:withBoolean:withNSString:withBoolean:withBoolean:);
  methods[1].selector = @selector(writeWithGsonJsonWriter:withId:);
  methods[2].selector = @selector(readWithGsonJsonReader:withId:);
  methods[3].selector = @selector(writeFieldWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "val$context_", "LGsonGson;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$field_", "LJavaLangReflectField;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$fieldType_", "LGsonTypeToken;", .constantValue.asLong = 0, 0x1012, -1, -1, 8, -1 },
    { "val$isPrimitive_", "Z", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "typeAdapter_", "LGsonTypeAdapter;", .constantValue.asLong = 0, 0x10, -1, -1, 9, -1 },
  };
  static const void *ptrTable[] = { "LNSString;ZZ", "write", "LGsonJsonWriter;LNSObject;", "LJavaIoIOException;LJavaLangIllegalAccessException;", "read", "LGsonJsonReader;LNSObject;", "writeField", "LNSObject;", "Lcom/google/gson/reflect/TypeToken<*>;", "Lcom/google/gson/TypeAdapter<*>;", "LGsonReflectiveTypeAdapterFactory;", "createBoundFieldWithGsonGson:withJavaLangReflectField:withNSString:withGsonTypeToken:withBoolean:withBoolean:" };
  static const J2ObjcClassInfo _GsonReflectiveTypeAdapterFactory_1 = { "", "com.google.gson.internal.bind", ptrTable, methods, fields, 7, 0x8018, 4, 5, 10, -1, 11, -1, -1 };
  return &_GsonReflectiveTypeAdapterFactory_1;
}

@end

void GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory_1 *self, GsonReflectiveTypeAdapterFactory *outer$, GsonGson *capture$0, JavaLangReflectField *capture$1, GsonTypeToken *capture$2, jboolean capture$3, NSString *name, jboolean serialized, jboolean deserialized) {
  self->val$context_ = capture$0;
  self->val$field_ = capture$1;
  self->val$fieldType_ = capture$2;
  self->val$isPrimitive_ = capture$3;
  GsonReflectiveTypeAdapterFactory_BoundField_initWithNSString_withBoolean_withBoolean_(self, name, serialized, deserialized);
  self->typeAdapter_ = GsonReflectiveTypeAdapterFactory_getFieldAdapterWithGsonGson_withJavaLangReflectField_withGsonTypeToken_(outer$, capture$0, capture$1, capture$2);
}

GsonReflectiveTypeAdapterFactory_1 *new_GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory *outer$, GsonGson *capture$0, JavaLangReflectField *capture$1, GsonTypeToken *capture$2, jboolean capture$3, NSString *name, jboolean serialized, jboolean deserialized) {
  J2OBJC_NEW_IMPL(GsonReflectiveTypeAdapterFactory_1, initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_, outer$, capture$0, capture$1, capture$2, capture$3, name, serialized, deserialized)
}

GsonReflectiveTypeAdapterFactory_1 *create_GsonReflectiveTypeAdapterFactory_1_initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(GsonReflectiveTypeAdapterFactory *outer$, GsonGson *capture$0, JavaLangReflectField *capture$1, GsonTypeToken *capture$2, jboolean capture$3, NSString *name, jboolean serialized, jboolean deserialized) {
  J2OBJC_CREATE_IMPL(GsonReflectiveTypeAdapterFactory_1, initWithGsonReflectiveTypeAdapterFactory_withGsonGson_withJavaLangReflectField_withGsonTypeToken_withBoolean_withNSString_withBoolean_withBoolean_, outer$, capture$0, capture$1, capture$2, capture$3, name, serialized, deserialized)
}

@implementation GsonReflectiveTypeAdapterFactory_Adapter

- (instancetype)initWithGsonObjectConstructor:(id<GsonObjectConstructor>)constructor
                              withJavaUtilMap:(id<JavaUtilMap>)boundFields {
  GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(self, constructor, boundFields);
  return self;
}

- (id)readWithGsonJsonReader:(GsonJsonReader *)inArg {
  if ([((GsonJsonReader *) nil_chk(inArg)) peek] == JreLoadEnum(GsonJsonToken, NULL)) {
    [inArg nextNull];
    return nil;
  }
  id instance = [((id<GsonObjectConstructor>) nil_chk(constructor_)) construct];
  @try {
    [inArg beginObject];
    while ([inArg hasNext]) {
      NSString *name = [inArg nextName];
      GsonReflectiveTypeAdapterFactory_BoundField *field = [((id<JavaUtilMap>) nil_chk(boundFields_)) getWithId:name];
      if (field == nil || !field->deserialized_) {
        [inArg skipValue];
      }
      else {
        [field readWithGsonJsonReader:inArg withId:instance];
      }
    }
  }
  @catch (JavaLangIllegalStateException *e) {
    @throw new_GsonJsonSyntaxException_initWithJavaLangThrowable_(e);
  }
  @catch (JavaLangIllegalAccessException *e) {
    @throw new_JavaLangAssertionError_initWithId_(e);
  }
  [inArg endObject];
  return instance;
}

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)outArg
                         withId:(id)value {
  if (value == nil) {
    (void) [((GsonJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  (void) [((GsonJsonWriter *) nil_chk(outArg)) beginObject];
  @try {
    for (GsonReflectiveTypeAdapterFactory_BoundField * __strong boundField in nil_chk([((id<JavaUtilMap>) nil_chk(boundFields_)) values])) {
      if ([((GsonReflectiveTypeAdapterFactory_BoundField *) nil_chk(boundField)) writeFieldWithId:value]) {
        (void) [outArg nameWithNSString:boundField->name_];
        [boundField writeWithGsonJsonWriter:outArg withId:value];
      }
    }
  }
  @catch (JavaLangIllegalAccessException *e) {
    @throw new_JavaLangAssertionError_init();
  }
  (void) [outArg endObject];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, 1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 2, 3, 4, 5, -1, -1 },
    { NULL, "V", 0x1, 6, 7, 4, 8, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithGsonObjectConstructor:withJavaUtilMap:);
  methods[1].selector = @selector(readWithGsonJsonReader:);
  methods[2].selector = @selector(writeWithGsonJsonWriter:withId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "constructor_", "LGsonObjectConstructor;", .constantValue.asLong = 0, 0x12, -1, -1, 9, -1 },
    { "boundFields_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x12, -1, -1, 10, -1 },
  };
  static const void *ptrTable[] = { "LGsonObjectConstructor;LJavaUtilMap;", "(Lcom/google/gson/internal/ObjectConstructor<TT;>;Ljava/util/Map<Ljava/lang/String;Lcom/google/gson/internal/bind/ReflectiveTypeAdapterFactory$BoundField;>;)V", "read", "LGsonJsonReader;", "LJavaIoIOException;", "(Lcom/google/gson/stream/JsonReader;)TT;", "write", "LGsonJsonWriter;LNSObject;", "(Lcom/google/gson/stream/JsonWriter;TT;)V", "Lcom/google/gson/internal/ObjectConstructor<TT;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/google/gson/internal/bind/ReflectiveTypeAdapterFactory$BoundField;>;", "LGsonReflectiveTypeAdapterFactory;", "<T:Ljava/lang/Object;>Lcom/google/gson/TypeAdapter<TT;>;" };
  static const J2ObjcClassInfo _GsonReflectiveTypeAdapterFactory_Adapter = { "Adapter", "com.google.gson.internal.bind", ptrTable, methods, fields, 7, 0x19, 3, 2, 11, -1, -1, 12, -1 };
  return &_GsonReflectiveTypeAdapterFactory_Adapter;
}

@end

void GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(GsonReflectiveTypeAdapterFactory_Adapter *self, id<GsonObjectConstructor> constructor, id<JavaUtilMap> boundFields) {
  GsonTypeAdapter_init(self);
  self->constructor_ = constructor;
  self->boundFields_ = boundFields;
}

GsonReflectiveTypeAdapterFactory_Adapter *new_GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(id<GsonObjectConstructor> constructor, id<JavaUtilMap> boundFields) {
  J2OBJC_NEW_IMPL(GsonReflectiveTypeAdapterFactory_Adapter, initWithGsonObjectConstructor_withJavaUtilMap_, constructor, boundFields)
}

GsonReflectiveTypeAdapterFactory_Adapter *create_GsonReflectiveTypeAdapterFactory_Adapter_initWithGsonObjectConstructor_withJavaUtilMap_(id<GsonObjectConstructor> constructor, id<JavaUtilMap> boundFields) {
  J2OBJC_CREATE_IMPL(GsonReflectiveTypeAdapterFactory_Adapter, initWithGsonObjectConstructor_withJavaUtilMap_, constructor, boundFields)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GsonReflectiveTypeAdapterFactory_Adapter)
