//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ReflectionAccessor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ReflectionAccessor")
#ifdef RESTRICT_ReflectionAccessor
#define INCLUDE_ALL_ReflectionAccessor 0
#else
#define INCLUDE_ALL_ReflectionAccessor 1
#endif
#undef RESTRICT_ReflectionAccessor

#if !defined (ComGoogleGsonInternalReflectReflectionAccessor_) && (INCLUDE_ALL_ReflectionAccessor || defined(INCLUDE_ComGoogleGsonInternalReflectReflectionAccessor))
#define ComGoogleGsonInternalReflectReflectionAccessor_

@class JavaLangReflectAccessibleObject;

@interface ComGoogleGsonInternalReflectReflectionAccessor : NSObject

#pragma mark Public

- (instancetype)init;

+ (ComGoogleGsonInternalReflectReflectionAccessor *)getInstance;

- (void)makeAccessibleWithJavaLangReflectAccessibleObject:(JavaLangReflectAccessibleObject *)ao;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonInternalReflectReflectionAccessor)

FOUNDATION_EXPORT void ComGoogleGsonInternalReflectReflectionAccessor_init(ComGoogleGsonInternalReflectReflectionAccessor *self);

FOUNDATION_EXPORT ComGoogleGsonInternalReflectReflectionAccessor *ComGoogleGsonInternalReflectReflectionAccessor_getInstance(void);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalReflectReflectionAccessor)

#endif

#pragma pop_macro("INCLUDE_ALL_ReflectionAccessor")
