//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TreeTypeAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TreeTypeAdapter")
#ifdef RESTRICT_TreeTypeAdapter
#define INCLUDE_ALL_TreeTypeAdapter 0
#else
#define INCLUDE_ALL_TreeTypeAdapter 1
#endif
#undef RESTRICT_TreeTypeAdapter

#if !defined (GsonTreeTypeAdapter_) && (INCLUDE_ALL_TreeTypeAdapter || defined(INCLUDE_GsonTreeTypeAdapter))
#define GsonTreeTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_GsonTypeAdapter 1
#include "TypeAdapter.h"

@class GsonJsonReader;
@class GsonJsonWriter;
@class GsonTypeToken;
@class IOSClass;
@protocol GsonTypeAdapterFactory;

@interface GsonTreeTypeAdapter : GsonTypeAdapter

#pragma mark Public

+ (id<GsonTypeAdapterFactory>)newFactoryWithGsonTypeToken:(GsonTypeToken *)exactType
                                                   withId:(id)typeAdapter OBJC_METHOD_FAMILY_NONE;

+ (id<GsonTypeAdapterFactory>)newFactoryWithMatchRawTypeWithGsonTypeToken:(GsonTypeToken *)exactType
                                                                   withId:(id)typeAdapter OBJC_METHOD_FAMILY_NONE;

+ (id<GsonTypeAdapterFactory>)newTypeHierarchyFactoryWithIOSClass:(IOSClass *)hierarchyType
                                                           withId:(id)typeAdapter OBJC_METHOD_FAMILY_NONE;

- (id)readWithGsonJsonReader:(GsonJsonReader *)inArg;

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)outArg
                         withId:(id)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonTreeTypeAdapter)

FOUNDATION_EXPORT id<GsonTypeAdapterFactory> GsonTreeTypeAdapter_newFactoryWithGsonTypeToken_withId_(GsonTypeToken *exactType, id typeAdapter);

FOUNDATION_EXPORT id<GsonTypeAdapterFactory> GsonTreeTypeAdapter_newFactoryWithMatchRawTypeWithGsonTypeToken_withId_(GsonTypeToken *exactType, id typeAdapter);

FOUNDATION_EXPORT id<GsonTypeAdapterFactory> GsonTreeTypeAdapter_newTypeHierarchyFactoryWithIOSClass_withId_(IOSClass *hierarchyType, id typeAdapter);

J2OBJC_TYPE_LITERAL_HEADER(GsonTreeTypeAdapter)

@compatibility_alias ComGoogleGsonTreeTypeAdapter GsonTreeTypeAdapter;

#endif

#pragma pop_macro("INCLUDE_ALL_TreeTypeAdapter")
