//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ArrayTypeAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ArrayTypeAdapter")
#ifdef RESTRICT_ArrayTypeAdapter
#define INCLUDE_ALL_ArrayTypeAdapter 0
#else
#define INCLUDE_ALL_ArrayTypeAdapter 1
#endif
#undef RESTRICT_ArrayTypeAdapter

#if !defined (GsonArrayTypeAdapter_) && (INCLUDE_ALL_ArrayTypeAdapter || defined(INCLUDE_GsonArrayTypeAdapter))
#define GsonArrayTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_GsonTypeAdapter 1
#include "TypeAdapter.h"

@class GsonGson;
@class GsonJsonReader;
@class GsonJsonWriter;
@class IOSClass;
@protocol GsonTypeAdapterFactory;

@interface GsonArrayTypeAdapter : GsonTypeAdapter

+ (id<GsonTypeAdapterFactory>)FACTORY;

#pragma mark Public

- (instancetype)initWithGsonGson:(GsonGson *)context
             withGsonTypeAdapter:(GsonTypeAdapter *)componentTypeAdapter
                    withIOSClass:(IOSClass *)componentType;

- (id)readWithGsonJsonReader:(GsonJsonReader *)inArg;

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)outArg
                         withId:(id)array;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(GsonArrayTypeAdapter)

inline id<GsonTypeAdapterFactory> GsonArrayTypeAdapter_get_FACTORY(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<GsonTypeAdapterFactory> GsonArrayTypeAdapter_FACTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GsonArrayTypeAdapter, FACTORY, id<GsonTypeAdapterFactory>)

FOUNDATION_EXPORT void GsonArrayTypeAdapter_initWithGsonGson_withGsonTypeAdapter_withIOSClass_(GsonArrayTypeAdapter *self, GsonGson *context, GsonTypeAdapter *componentTypeAdapter, IOSClass *componentType);

FOUNDATION_EXPORT GsonArrayTypeAdapter *new_GsonArrayTypeAdapter_initWithGsonGson_withGsonTypeAdapter_withIOSClass_(GsonGson *context, GsonTypeAdapter *componentTypeAdapter, IOSClass *componentType) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonArrayTypeAdapter *create_GsonArrayTypeAdapter_initWithGsonGson_withGsonTypeAdapter_withIOSClass_(GsonGson *context, GsonTypeAdapter *componentTypeAdapter, IOSClass *componentType);

J2OBJC_TYPE_LITERAL_HEADER(GsonArrayTypeAdapter)

@compatibility_alias ComGoogleGsonInternalBindArrayTypeAdapter GsonArrayTypeAdapter;

#endif

#pragma pop_macro("INCLUDE_ALL_ArrayTypeAdapter")
