//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ExclusionStrategy.java
//

#ifndef ExclusionStrategy_H
#define ExclusionStrategy_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class GsonFieldAttributes;
@class IOSClass;

@protocol GsonExclusionStrategy < JavaObject >

- (jboolean)shouldSkipFieldWithGsonFieldAttributes:(GsonFieldAttributes *)f;

- (jboolean)shouldSkipClassWithIOSClass:(IOSClass *)clazz;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonExclusionStrategy)

J2OBJC_TYPE_LITERAL_HEADER(GsonExclusionStrategy)

#define ComGoogleGsonExclusionStrategy GsonExclusionStrategy


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // ExclusionStrategy_H
