//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/FieldAttributes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FieldAttributes")
#ifdef RESTRICT_FieldAttributes
#define INCLUDE_ALL_FieldAttributes 0
#else
#define INCLUDE_ALL_FieldAttributes 1
#endif
#undef RESTRICT_FieldAttributes

#if !defined (GsonFieldAttributes_) && (INCLUDE_ALL_FieldAttributes || defined(INCLUDE_GsonFieldAttributes))
#define GsonFieldAttributes_

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;
@protocol JavaLangReflectType;
@protocol JavaUtilCollection;

@interface GsonFieldAttributes : NSObject

#pragma mark Public

- (instancetype)initWithJavaLangReflectField:(JavaLangReflectField *)f;

- (id<JavaLangAnnotationAnnotation>)getAnnotationWithIOSClass:(IOSClass *)annotation;

- (id<JavaUtilCollection>)getAnnotations;

- (IOSClass *)getDeclaredClass;

- (id<JavaLangReflectType>)getDeclaredType;

- (IOSClass *)getDeclaringClass;

- (NSString *)getName;

- (jboolean)hasModifierWithInt:(jint)modifier;

#pragma mark Package-Private

- (id)getWithId:(id)instance;

- (jboolean)isSynthetic;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonFieldAttributes)

FOUNDATION_EXPORT void GsonFieldAttributes_initWithJavaLangReflectField_(GsonFieldAttributes *self, JavaLangReflectField *f);

FOUNDATION_EXPORT GsonFieldAttributes *new_GsonFieldAttributes_initWithJavaLangReflectField_(JavaLangReflectField *f) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonFieldAttributes *create_GsonFieldAttributes_initWithJavaLangReflectField_(JavaLangReflectField *f);

J2OBJC_TYPE_LITERAL_HEADER(GsonFieldAttributes)

@compatibility_alias ComGoogleGsonFieldAttributes GsonFieldAttributes;

#endif

#pragma pop_macro("INCLUDE_ALL_FieldAttributes")
