//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/FieldNamingStrategy.java
//

#ifndef FieldNamingStrategy_H
#define FieldNamingStrategy_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class JavaLangReflectField;

@protocol GsonFieldNamingStrategy < JavaObject >

- (NSString *)translateNameWithJavaLangReflectField:(JavaLangReflectField *)f;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonFieldNamingStrategy)

J2OBJC_TYPE_LITERAL_HEADER(GsonFieldNamingStrategy)

#define ComGoogleGsonFieldNamingStrategy GsonFieldNamingStrategy


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // FieldNamingStrategy_H
