//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonTreeReader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonTreeReader")
#ifdef RESTRICT_JsonTreeReader
#define INCLUDE_ALL_JsonTreeReader 0
#else
#define INCLUDE_ALL_JsonTreeReader 1
#endif
#undef RESTRICT_JsonTreeReader

#if !defined (GsonJsonTreeReader_) && (INCLUDE_ALL_JsonTreeReader || defined(INCLUDE_GsonJsonTreeReader))
#define GsonJsonTreeReader_

#define RESTRICT_JsonReader 1
#define INCLUDE_GsonJsonReader 1
#include "JsonReader.h"

@class GsonJsonElement;
@class GsonJsonToken;
@class JavaIoReader;

@interface GsonJsonTreeReader : GsonJsonReader

#pragma mark Public

- (instancetype)initWithGsonJsonElement:(GsonJsonElement *)element;

- (void)beginArray;

- (void)beginObject;

- (void)close;

- (void)endArray;

- (void)endObject;

- (NSString *)getPath;

- (jboolean)hasNext;

- (jboolean)nextBoolean;

- (jdouble)nextDouble;

- (jint)nextInt;

- (jlong)nextLong;

- (NSString *)nextName;

- (void)nextNull;

- (NSString *)nextString;

- (GsonJsonToken *)peek;

- (void)promoteNameToValue;

- (void)skipValue;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithJavaIoReader:(JavaIoReader *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(GsonJsonTreeReader)

FOUNDATION_EXPORT void GsonJsonTreeReader_initWithGsonJsonElement_(GsonJsonTreeReader *self, GsonJsonElement *element);

FOUNDATION_EXPORT GsonJsonTreeReader *new_GsonJsonTreeReader_initWithGsonJsonElement_(GsonJsonElement *element) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonTreeReader *create_GsonJsonTreeReader_initWithGsonJsonElement_(GsonJsonElement *element);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonTreeReader)

@compatibility_alias ComGoogleGsonInternalBindJsonTreeReader GsonJsonTreeReader;

#endif

#pragma pop_macro("INCLUDE_ALL_JsonTreeReader")
