//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonSerializer.java
//

#ifndef JsonSerializer_H
#define JsonSerializer_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class GsonJsonElement;
@protocol GsonJsonSerializationContext;
@protocol JavaLangReflectType;

@protocol GsonJsonSerializer < JavaObject >

- (GsonJsonElement *)serializeWithId:(id)src
             withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withGsonJsonSerializationContext:(id<GsonJsonSerializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonJsonSerializer)

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonSerializer)

#define ComGoogleGsonJsonSerializer GsonJsonSerializer


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JsonSerializer_H
