//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonParseException.java
//

#ifndef JsonParseException_H
#define JsonParseException_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

@interface GsonJsonParseException : JavaLangRuntimeException
@property (readonly, class) jlong serialVersionUID NS_SWIFT_NAME(serialVersionUID);

+ (jlong)serialVersionUID;

#pragma mark Public

- (instancetype __nonnull)initWithNSString:(NSString *)msg;

- (instancetype __nonnull)initWithNSString:(NSString *)msg
                     withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1
                               withBoolean:(jboolean)arg2
                               withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonJsonParseException)

inline jlong GsonJsonParseException_get_serialVersionUID(void);
#define GsonJsonParseException_serialVersionUID -4086729973971783390LL
J2OBJC_STATIC_FIELD_CONSTANT(GsonJsonParseException, serialVersionUID, jlong)

FOUNDATION_EXPORT void GsonJsonParseException_initWithNSString_(GsonJsonParseException *self, NSString *msg);

FOUNDATION_EXPORT GsonJsonParseException *new_GsonJsonParseException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonParseException *create_GsonJsonParseException_initWithNSString_(NSString *msg);

FOUNDATION_EXPORT void GsonJsonParseException_initWithNSString_withJavaLangThrowable_(GsonJsonParseException *self, NSString *msg, JavaLangThrowable *cause);

FOUNDATION_EXPORT GsonJsonParseException *new_GsonJsonParseException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonParseException *create_GsonJsonParseException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause);

FOUNDATION_EXPORT void GsonJsonParseException_initWithJavaLangThrowable_(GsonJsonParseException *self, JavaLangThrowable *cause);

FOUNDATION_EXPORT GsonJsonParseException *new_GsonJsonParseException_initWithJavaLangThrowable_(JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonParseException *create_GsonJsonParseException_initWithJavaLangThrowable_(JavaLangThrowable *cause);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonParseException)

@compatibility_alias ComGoogleGsonJsonParseException GsonJsonParseException;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JsonParseException_H
