//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonParser.java
//

#ifndef JsonParser_H
#define JsonParser_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class GsonJsonElement;
@class GsonJsonReader;
@class JavaIoReader;

@interface GsonJsonParser : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (GsonJsonElement *)parseWithGsonJsonReader:(GsonJsonReader *)json;

- (GsonJsonElement *)parseWithJavaIoReader:(JavaIoReader *)json;

- (GsonJsonElement *)parseWithNSString:(NSString *)json;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonJsonParser)

FOUNDATION_EXPORT void GsonJsonParser_init(GsonJsonParser *self);

FOUNDATION_EXPORT GsonJsonParser *new_GsonJsonParser_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonParser *create_GsonJsonParser_init(void);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonParser)

@compatibility_alias ComGoogleGsonJsonParser GsonJsonParser;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JsonParser_H
