//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonNull.java
//

#ifndef JsonNull_H
#define JsonNull_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "JsonElement.h"

@interface GsonJsonNull : GsonJsonElement
@property (readonly, class) GsonJsonNull *INSTANCE NS_SWIFT_NAME(INSTANCE);

+ (GsonJsonNull *)INSTANCE;

#pragma mark Public

- (instancetype __nonnull)init;

- (GsonJsonNull *)deepCopy;

- (jboolean)isEqual:(id)other;

- (NSUInteger)hash;

@end

J2OBJC_STATIC_INIT(GsonJsonNull)

inline GsonJsonNull *GsonJsonNull_get_INSTANCE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT GsonJsonNull *GsonJsonNull_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GsonJsonNull, INSTANCE, GsonJsonNull *)

FOUNDATION_EXPORT void GsonJsonNull_init(GsonJsonNull *self);

FOUNDATION_EXPORT GsonJsonNull *new_GsonJsonNull_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonNull *create_GsonJsonNull_init(void);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonNull)

@compatibility_alias ComGoogleGsonJsonNull GsonJsonNull;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JsonNull_H
