//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonAdapterAnnotationTypeAdapterFactory.java
//

#ifndef JsonAdapterAnnotationTypeAdapterFactory_H
#define JsonAdapterAnnotationTypeAdapterFactory_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "TypeAdapterFactory.h"

@class GsonConstructorConstructor;
@class GsonGson;
@class GsonTypeAdapter;
@class GsonTypeToken;
@protocol GsonJsonAdapter;

@interface GsonJsonAdapterAnnotationTypeAdapterFactory : NSObject < GsonTypeAdapterFactory >

#pragma mark Public

- (instancetype __nonnull)initWithGsonConstructorConstructor:(GsonConstructorConstructor *)constructorConstructor;

- (GsonTypeAdapter *)createWithGsonGson:(GsonGson *)gson
                      withGsonTypeToken:(GsonTypeToken *)targetType;

#pragma mark Package-Private

- (GsonTypeAdapter *)getTypeAdapterWithGsonConstructorConstructor:(GsonConstructorConstructor *)constructorConstructor
                                                     withGsonGson:(GsonGson *)gson
                                                withGsonTypeToken:(GsonTypeToken *)type
                                              withGsonJsonAdapter:(id<GsonJsonAdapter>)annotation;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonJsonAdapterAnnotationTypeAdapterFactory)

FOUNDATION_EXPORT void GsonJsonAdapterAnnotationTypeAdapterFactory_initWithGsonConstructorConstructor_(GsonJsonAdapterAnnotationTypeAdapterFactory *self, GsonConstructorConstructor *constructorConstructor);

FOUNDATION_EXPORT GsonJsonAdapterAnnotationTypeAdapterFactory *new_GsonJsonAdapterAnnotationTypeAdapterFactory_initWithGsonConstructorConstructor_(GsonConstructorConstructor *constructorConstructor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonAdapterAnnotationTypeAdapterFactory *create_GsonJsonAdapterAnnotationTypeAdapterFactory_initWithGsonConstructorConstructor_(GsonConstructorConstructor *constructorConstructor);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonAdapterAnnotationTypeAdapterFactory)

@compatibility_alias ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory GsonJsonAdapterAnnotationTypeAdapterFactory;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JsonAdapterAnnotationTypeAdapterFactory_H
