//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/LazilyParsedNumber.java
//

#ifndef LazilyParsedNumber_H
#define LazilyParsedNumber_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@interface GsonLazilyParsedNumber : NSNumber

#pragma mark Public

- (instancetype __nonnull)initWithNSString:(NSString *)value;

- (jdouble)doubleValue;

- (jboolean)isEqual:(id)obj;

- (jfloat)floatValue;

- (NSUInteger)hash;

- (jint)intValue;

- (jlong)longLongValue;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonLazilyParsedNumber)

FOUNDATION_EXPORT void GsonLazilyParsedNumber_initWithNSString_(GsonLazilyParsedNumber *self, NSString *value);

FOUNDATION_EXPORT GsonLazilyParsedNumber *new_GsonLazilyParsedNumber_initWithNSString_(NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonLazilyParsedNumber *create_GsonLazilyParsedNumber_initWithNSString_(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(GsonLazilyParsedNumber)

@compatibility_alias ComGoogleGsonInternalLazilyParsedNumber GsonLazilyParsedNumber;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // LazilyParsedNumber_H
