//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/LongSerializationPolicy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LongSerializationPolicy")
#ifdef RESTRICT_LongSerializationPolicy
#define INCLUDE_ALL_LongSerializationPolicy 0
#else
#define INCLUDE_ALL_LongSerializationPolicy 1
#endif
#undef RESTRICT_LongSerializationPolicy

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GsonLongSerializationPolicy_) && (INCLUDE_ALL_LongSerializationPolicy || defined(INCLUDE_GsonLongSerializationPolicy))
#define GsonLongSerializationPolicy_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class GsonJsonElement;
@class IOSObjectArray;
@class JavaLangLong;

typedef NS_ENUM(NSUInteger, GsonLongSerializationPolicy_Enum) {
  GsonLongSerializationPolicy_Enum_DEFAULT = 0,
  GsonLongSerializationPolicy_Enum_STRING = 1,
};

@interface GsonLongSerializationPolicy : JavaLangEnum

+ (GsonLongSerializationPolicy * __nonnull)DEFAULT;

+ (GsonLongSerializationPolicy * __nonnull)STRING;

#pragma mark Public

- (GsonJsonElement *)serializeWithJavaLangLong:(JavaLangLong *)value;

+ (GsonLongSerializationPolicy *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (GsonLongSerializationPolicy_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(GsonLongSerializationPolicy)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT GsonLongSerializationPolicy *GsonLongSerializationPolicy_values_[];

inline GsonLongSerializationPolicy *GsonLongSerializationPolicy_get_DEFAULT(void);
J2OBJC_ENUM_CONSTANT(GsonLongSerializationPolicy, DEFAULT)

inline GsonLongSerializationPolicy *GsonLongSerializationPolicy_get_STRING(void);
J2OBJC_ENUM_CONSTANT(GsonLongSerializationPolicy, STRING)

FOUNDATION_EXPORT IOSObjectArray *GsonLongSerializationPolicy_values(void);

FOUNDATION_EXPORT GsonLongSerializationPolicy *GsonLongSerializationPolicy_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT GsonLongSerializationPolicy *GsonLongSerializationPolicy_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(GsonLongSerializationPolicy)

@compatibility_alias ComGoogleGsonLongSerializationPolicy GsonLongSerializationPolicy;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_LongSerializationPolicy")
