//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SqlDateTypeAdapter.java
//

#ifndef SqlDateTypeAdapter_H
#define SqlDateTypeAdapter_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "TypeAdapter.h"

@class GsonJsonElement;
@class GsonJsonReader;
@class GsonJsonWriter;
@class JavaIoReader;
@class JavaSqlDate;
@protocol GsonTypeAdapterFactory;

@interface GsonSqlDateTypeAdapter : GsonTypeAdapter
@property (readonly, class) id<GsonTypeAdapterFactory> FACTORY NS_SWIFT_NAME(FACTORY);

+ (id<GsonTypeAdapterFactory>)FACTORY;

#pragma mark Public

- (instancetype __nonnull)init;

- (JavaSqlDate *)fromJsonTreeWithGsonJsonElement:(GsonJsonElement *)arg0;

- (JavaSqlDate *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (JavaSqlDate *)fromJsonWithNSString:(NSString *)arg0;

- (JavaSqlDate *)readWithGsonJsonReader:(GsonJsonReader *)inArg;

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)outArg
                         withId:(JavaSqlDate *)value;

@end

J2OBJC_STATIC_INIT(GsonSqlDateTypeAdapter)

inline id<GsonTypeAdapterFactory> GsonSqlDateTypeAdapter_get_FACTORY(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<GsonTypeAdapterFactory> GsonSqlDateTypeAdapter_FACTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GsonSqlDateTypeAdapter, FACTORY, id<GsonTypeAdapterFactory>)

FOUNDATION_EXPORT void GsonSqlDateTypeAdapter_init(GsonSqlDateTypeAdapter *self);

FOUNDATION_EXPORT GsonSqlDateTypeAdapter *new_GsonSqlDateTypeAdapter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonSqlDateTypeAdapter *create_GsonSqlDateTypeAdapter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(GsonSqlDateTypeAdapter)

@compatibility_alias ComGoogleGsonInternalBindSqlDateTypeAdapter GsonSqlDateTypeAdapter;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // SqlDateTypeAdapter_H
