//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/UnsafeReflectionAccessor.java
//

#ifndef UnsafeReflectionAccessor_H
#define UnsafeReflectionAccessor_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "ReflectionAccessor.h"

@class JavaLangReflectAccessibleObject;

@interface ComGoogleGsonInternalReflectUnsafeReflectionAccessor : ComGoogleGsonInternalReflectReflectionAccessor

#pragma mark Public

- (void)makeAccessibleWithJavaLangReflectAccessibleObject:(JavaLangReflectAccessibleObject *)ao;

#pragma mark Package-Private

- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalReflectUnsafeReflectionAccessor)

FOUNDATION_EXPORT void ComGoogleGsonInternalReflectUnsafeReflectionAccessor_init(ComGoogleGsonInternalReflectUnsafeReflectionAccessor *self);

FOUNDATION_EXPORT ComGoogleGsonInternalReflectUnsafeReflectionAccessor *new_ComGoogleGsonInternalReflectUnsafeReflectionAccessor_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleGsonInternalReflectUnsafeReflectionAccessor *create_ComGoogleGsonInternalReflectUnsafeReflectionAccessor_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalReflectUnsafeReflectionAccessor)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // UnsafeReflectionAccessor_H
