//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Until.java
//

#ifndef Until_H
#define Until_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol GsonUntil < JavaLangAnnotationAnnotation >

@property (readonly) jdouble value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface GsonUntil : NSObject < GsonUntil > {
 @public
  jdouble value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(GsonUntil)

FOUNDATION_EXPORT id<GsonUntil> create_GsonUntil(jdouble value);

J2OBJC_TYPE_LITERAL_HEADER(GsonUntil)

#define ComGoogleGsonAnnotationsUntil GsonUntil


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // Until_H
